# Generated by Django 4.1 on 2024-07-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True)),
                ('description', models.CharField(max_length=500)),
                ('sqrt', models.BigIntegerField()),
                ('divisors', models.JSONField()),
                ('is_even', models.BooleanField()),
            ],
        ),
    ]
