# Generated by Django 4.1 on 2024-07-03 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynumbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='numberinfo',
            name='description',
        ),
        migrations.AlterField(
            model_name='numberinfo',
            name='number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mynumbers.number'),
        ),
    ]
