# Generated by Django 4.1 on 2024-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynumbers', '0002_number_remove_numberinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberinfo',
            name='sqrt',
            field=models.FloatField(),
        ),
    ]
